name: denv_desktop
description: Aplicación para la detección y monitoreo de zonas con mosquitos que causan el Dengue en el Perú.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dio: ^5.3.2
  equatable: ^2.0.5
  file_saver: ^0.2.7
  fluent_ui: ^4.7.1
  flutter:
    sdk: flutter    
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_lorem: ^2.0.0
  inspection_api:
    path: packages/inspection_api
  inspection_api_remote:
    path: packages/inspection_api_remote
  inspection_repository:
    path: packages/inspection_repository
  intl: ^0.18.0
  local_api:
    path: packages/local_api
  local_api_remote:
    path: packages/local_api_remote
  local_repository:
    path: packages/local_repository
  shared_preferences: ^2.2.0
  syncfusion_flutter_core: ^22.2.7
  syncfusion_flutter_datagrid: ^22.2.7
  syncfusion_flutter_datagrid_export: ^22.2.11
  syncfusion_flutter_maps: ^22.2.7
  syncfusion_flutter_pdf: ^22.2.7
  syncfusion_flutter_xlsio: ^22.2.7
  text_scroll: ^0.2.0

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  msix: ^3.16.1
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
   - assets/icon/
   - assets/map_grids/
   - assets/images/
   - .env

flutter_icons:
  android: false
  ios: false
  image_path: "assets/icon/denv_icon.png"
  web:
    generate: true
    image_path: "assets/icon/denv_icon.png"
  windows:
    generate: true
    image_path: "assets/icon/denv_icon.png"
    icon_size: 256

msix_config:
  display_name: DENV Desktop
  publisher_display_name: Piero Angelo Morales Alcalde
  identity_name: 29622PieroAngeloMoralesAl.DENVDesktop
  publisher: CN=91BE0923-E8F6-4F62-AE9E-2A123C9AC1AF
  msix_version: 1.0.0.1
  languages: es-es, en-us
  logo_path: assets/icon/denv_icon_windows.png
  store: true
