name: inspection_repository
description: Repositorio de comunicación con backend de las inspecciones de viviendas
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.10.6

dependencies:
  flutter:
    sdk: flutter
  inspection_api:
    path: ../inspection_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0+1
